pipeline{
    agent any
    stages {
        stage('Test Parallel') {
            parallel {
                stage('Test on Win') {
                    steps {
                       echo 'Test on Windows'
                    }    
                }
                stage('Test on Lin') {
                    steps {
                        echo 'Test on Linux'
                        echo env.GIT_BRANCH
                    }
                }
            }
        }
        stage('Test when') {
            when {
                env.GIT_BRANCH 'origin/master'
            }
            steps {
                echo 'Testing when'
            }
        }

    }
}

