pipeline{
    agent any
    stages {
        stage('Test Parallel') {
            environment { 
                GIT_BRANCH = "${GIT_BRANCH.split("/")[1]}"
            }
            parallel {
                stage('Test on Win') {
                    steps {
                       echo 'Test on Windows'
                    }    
                }
                stage('Test on Lin') {
                    steps {
                        echo 'Test on Linux'
                        echo env.GIT_BRANCH
                    }
                }
            }
        }
        stage('Test when') {
            
            when {
                branch "origin/master"
            }
            steps {
                echo 'Testing when'
            }
        }

    }
}

